# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17V_3rP1FEkSA5Wc798IxVkEju_K0szU7
"""

import numpy as np
import numpy.polynomial.polynomial as nppol
import matplotlib.pyplot as plt
import math

"""1. Création de fonction mathématique simple en Python (12 points) :"""

x = int(input("la valeur a calculer dans le polynom "))

a) Implémenter la fonction polynomiale ci-dessous :

def F(x):
    return (x**3)-(1.5*x**2)-(6*x)+5

"""test code 

"""

print(F(x))

"""b) Implémenter la fonction factorielle (Approche récursive ou classique)"""

n = int(input("la valeur a calculer en factoriel "))

def fact(n):
   if n == 0:
      return 1
   else:
      F = 1
      for k in range(2,n+1):
         F = F * k
      return F

"""test  du code """

print(fact(n))

"""c) Implémenter la suite de Fibonnaci"""

def fib(a):
    if(a <= 1):
        return a
    else:
        return (fib(a-1) + fib(a-2))
a = int(input("Entrez le nombre "))
print("Suite de Fibonacci est :")
for i in range(a):
    print(fib(i))

"""2. Création de fonction comportant des modules de gestions des
exceptions (5 points) :

- Saisie d'une chaine de caractère dans les arguments de la fonction
"""

borne_max = 999999
borne_min = 0.00001
n = int(input("la valeur a calculer en factoriel "))
def fact(n):

##### si n un str #####
 if (type(n)==str):

  print("il est impossible d'effectuer le calcul avec un str ")
  print("VEUILLER SAISSIR UNE NOUVELLE VALEUR DE TYPE NUMERIQUE")
  n = int(input("la valeur a calculer en factoriel "))

    ##### cas des nombre complexes#####  
if (type(n) == complex):
                        
 print("il est impossible d'effectuer le calcul avec un nombre complexe")
print("VEUILLEZ SAISSIR A NOUVEAU VOS VALEUR") 
n = int(input("la valeur a calculer en factoriel ")) 


   ##### cas ou la valeur de n est null ou negatif#####  
if (n<=0) :

  print("le calcule ne peut pas etre effectuer avec un nombre nul ou infferieur a zero")  
  print("VEUILLEZ SAISSIR A NOUVEAU VOS VALEUR")
  n = int(input("la valeur a calculer en factoriel "))

  ##### cas ou les nombres sont trés grands#####
if(n> borne_max):

  print("vous depassez la borne max de calcul")
  print("saissir de nouvelle valeur")
  n = int(input("la valeur a calculer en factoriel "))

   ##### cas ou les nombres sont trop petit #####
if (n< borne_min):

 print("vous etes inferieur au borne min de calcul")
 print("saissir de nouvelle valeur") 
 n = int(input("la valeur a calculer en factoriel "))
   

else:
    print(fact(n))

"""3. Question Bonus : Implémentation de la formule Pricer d’option avec
Python

"""

from math import log, sqrt, pi, exp
from scipy.stats import norm
from datetime import datetime, date
import numpy as np
import pandas as pd
from pandas import DataFrame

def d1(S,K,T,r,sigma):
    return(log(S/K)+(r+sigma**2/2.)*T)/(sigma*sqrt(T))
def d2(S,K,T,r,sigma):
    return d1(S,K,T,r,sigma)-sigma*sqrt(T)

def bs_call(S,K,T,r,sigma):
    return S*norm.cdf(d1(S,K,T,r,sigma))-K*exp(-r*T)*norm.cdf(d2(S,K,T,r,sigma))
  
def bs_put(S,K,T,r,sigma):
    return K*exp(-r*T)-S+bs_call(S,K,T,r,sigma)